### ISSUE TITLE
Cannot read property 'isEntry' of undefined rollup@2.0.0

### ISSUE THREAD

**Issue by kapilpipaliya** [haifeng2013/rollup-plugin-bundle-html#31]
```
[!] (plugin html) TypeError: Cannot read property 'isEntry' of undefined
TypeError: Cannot read property 'isEntry' of undefined
    at node_modules/rollup-plugin-bundle-html/dist/index.cjs.js:221:11
    at Array.forEach (<anonymous>)
    at Object.writeBundle (node_modules/rollup-plugin-bundle-html/dist/index.cjs.js:220:26)
    at node_modules/rollup/dist/shared/rollup.js:17408:25
    at async Promise.all (index 0)
    at node_modules/rollup/dist/shared/rollup.js:18175:17
    at async Promise.all (index 0)
    at Task.run (node_modules/rollup/dist/shared/watch.js:7036:13)
    at Watcher.run (node_modules/rollup/dist/shared/watch.js:6956:17)
```
I get above error when upgrade rollup from 1.32.1 to 2.0.0

**Comment by NetOpWibby** [comment]
AHA so that's the problem!

**Comment by NetOpWibby** [comment]
This repo seems to be abandoned, time to find an alternative.

EDIT: [This](https://github.com/mentaljam/rollup-plugin-html2) seems to work. You're gonna have to look at the examples to get it working for your project.

**Comment by kapilpipaliya** [comment]
Thanks. I used [replace-in-file](https://www.npmjs.com/package/replace-in-filehttps://www.npmjs.com/package/replace-in-file)

**Comment by jvalecillos** [comment]
Same issue here. Looking for a solution or alternatives.

**Comment by raphet** [comment]
Damn it, why did I spend 1h hitting my head until I found this issue here. Thank you guys. Same here. And also thanks for the suggested alternatives!

**Comment by AndresHermosodeMendoza** [comment]
Well, i am not a profesional here but i found a way to use it without sourcemaps. i just check a little bit the code source and it can be fixed. The code i change doesnt make too much diference. It works but just for simple use, not for advanced options (yet). Dont know if im going to fix it at all but i left you file with the code change  [here](https://github.com/AndresHermosodeMendoza/rollup-plugin-bundle-html-fixed)
Im not sure the behavior it will take for the diferents configs, play with it and try
